swagger: "2.0"

# this looks like an ok place to start for a sample:
# https://github.com/zalando/connexion/blob/master/examples/restyresolver/resty-api.yaml

info:
  title: "{{title}}"
  version: "1.0"

basePath: /v1.0

paths:
  /greeting/{name}:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: api.post_greeting
      produces:
        - text/plain;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello John"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
  /user/{username}:
    get:
      summary: Get user
      description: Get user.
      operationId: api.get_user
      produces:
        - application/json;
      responses:
        200:
          description: get user response
          schema:
            $ref: '#/definitions/User'
          examples:
            "application/json": '{"email":"admin@example.com","id":1,"username":"admin"}'
      parameters:
        - name: username
          in: path
          description: Name of the user to retrieve.
          required: true
          type: string
definitions:
  User:
    type: object
    properties:
      id: { type: integer, format: int32 }
      username: { type: string }
      email: { type: string }
